### ISSUE TITLE
On Ubuntu 18.04 (Gnome Shell 3.28.2) Keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by leorochael** [wbolster/nothing-to-say#16]
Either by installing from the gnome extensions site or as a symlink to a checkout of the github repository.

All the other functionality works as advertised (it's very nice, by the way!).

I tried manually setting the default keyboard shortcut with the command documented in the README:

    dconf write /org/gnome/shell/extensions/nothing-to-say/keybinding-toggle-mute '["<Super>backslash"]'

But that didn't help.

Looking at `dconf editor` after that command shows that there is no schema loaded:

![image](https://user-images.githubusercontent.com/239125/52134301-6b2b6a00-262a-11e9-838b-df28d23e89bb.png)

How do I make the keyboard shortcut (or any keyboard shorcut) work?

**Comment by leorochael** [comment]
Further experimentation shows that it's the default shortcut that doesn't work. Other shorcuts like `<Control>Pause` seem to work.

**Comment by wbolster** [comment]
glad that it works for you now :)

maybe something else claimed that keybinding? or your keyboard layout?

**Comment by leorochael** [comment]
> maybe something else claimed that keybinding? or your keyboard layout?

No, it's not any of those things. And now I feel really stupid...

The problem is that I misinterpreted `backslash` as `backspace`.

And here I was wondering, all this time: "why the heck would @wbolster chose a default shortcut that couldn't possibly ever be typed with a single hand? Was it just to make a point for people to chose their own shortcuts? He did say he didn't like it..."

**Comment by wbolster** [comment]
haha 👌😎

the default is a bit weird, but it's hard to come up with a sensible default that does not clash with gnome's defaults. so i ended up picking a weird default out of laziness and then immediately decided i hated it. ah well. this whole extension has a tongue-in-cheek vibe to it anyway. :)

(and since i personally use colemak and a completely customized set of keybindings for gnome, what i find convenient is likely not very useable for anyone but me anyway.)
