### ISSUE TITLE
Gnome 40 + gtk 4 compatibility issue

### ISSUE THREAD

**Issue by rudolfkastl** [wbolster/nothing-to-say#36]
Error: No property margin on GtkGrid

```
Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  buildPrefsWidget@/home/rkastl/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/prefs.js:23:23
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
````

This should be helpful:
https://developer.gnome.org/gtk4/stable/gtk-migrating-3-to-4.html

**Comment by wbolster** [comment]
i added fairly minimal gnome 40 support in beb0fd93602337aacddd8bd43020587d9138b83a

i've uploaded a new version to https://extensions.gnome.org/ which should hopefully appear soon.

this new version is only compatible with gnome 40, because i have no time (and no expertise) to maintain compatibility with multiple gnome versions. as i understand it, the gnome extension website will offer older versions to older gnome versions, so things should keep working.
