### ISSUE TITLE
Gnome crash with Wayland

### ISSUE THREAD

**Issue by JJ-8** [wbolster/nothing-to-say#49]
Since the update yesterday this extensions causes a hard-crash of gnome in Wayland. 

Yesterday I have updated nothing to say and after a reboot, gnome fully freezes just after the login. I can not move my mouse and nothing reacts to input anymore. After about 3 minutes, gnome detects this fatal crash and terminates back to the login screen. After that, all extensions are disabled. If I try to re-enable my extensions, then the same freeze happens but gnome will not detect this and I am stuck until I force reboot.
Opening a session in Xorg works perfectly fine and there I can disable nothing to say so I can launch into Wayland again. (Due to drivers I have to use Wayland in order to use my device properly).

I have debugged this problem for a couple of hours but I couldn't find any root causes besides the fatal freeze when enabling this extension. Running `$ journalctl -b -f /usr/bin/gnome-shell` while installing/enabling the extension does _not_ give any output. If I look back at the logs after a reboot, I can also not find any errors.
I tried installing v14/13 again manually, but both do now crash my system in Wayland. Again, Xorg works perfectly fine.

Since this extension is the only extension that causes this behaviour, I have opened an issue here.

**Comment by wbolster** [comment]
weird, doesn't ring a bell at all. using our myself on recent gnome on wayland without error

**Comment by wbolster** [comment]
see also #47, not sure if related

**Comment by JJ-8** [comment]
I don't think that issue is related, since it is not just an error but a real fatal crash... :/
Maybe it could be related to an older version of gnome since the one of Ubuntu 20.04 is already pretty old?

**Comment by wbolster** [comment]
could be, recent version introduced sound effects so it may touch different libraries

**Comment by mattaustin** [comment]
Just noting that I think I have encountered the same issue with a GNOME 42 wayland session on Ubuntu 22.04 beta.

**Comment by JJ-8** [comment]
@mattaustin, that is very unfortunate. I was hoping that upgrading to Ubuntu 22.04 next month would solve this issue :disappointed: 
Do you have any crash in `journalctl`? Or another log that may indicate the problem? I couldn't find it anywhere on my system...

**Comment by mattaustin** [comment]
I originally filed a bug in mutter, as I didn't realise it was caused by a gnome extension (I just thought the wayland session had stopped working in one of the beta updates - and I wasn't patient enough to wait the period before being returned to the login screen - I thought it was a hard crash). But sure enough, disabling this extension fixed the issue.

I didn't see too much of interest in my journalctl output either, I attached it to the ubuntu bug:
https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1966921

**Comment by wbolster** [comment]
fyi, in the mean time i'm on gnome 42 + wayland myself and i experience no issues, so i can't be of help

**Comment by adamchabin** [comment]
Looks like after today's Ubuntu 20.04 update nothing to say started working.

**Comment by benblasco** [comment]
I had the exact same problem described in the original post in the following setup:
Fedora 36
Gnome 42 on Wayland
Lenovo X1 Carbon Gen 9

Unfortunately I don't know how to collect logs from before the crash.  I resolved the issue by removing the extension altogether when logging in via X instead of Wayland.

Would be happy to take some guidance to test this further and collect the data to help resolve this issue for others.  Can anybody point me in the right direction for data collection from the crashed Gnome session?

**Comment by JJ-8** [comment]
Today I have upgraded to Ubuntu 22.04 LTS. Now I am able to use nothing to say again. I have no clue what could have caused the issue, but it is gone now while still using Wayland! :tada: 
```
➜ gnome-shell --version
GNOME Shell 42.2
```
